server:
  port: ${port} #服务端口

spring:
  application:
    name: itcast-microservice-order
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# = = = = = = = = = = = = = = = == = = = = = = = = = == = = = = = = = = = = = = = =
#数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: MyNewPass
    maxActive: 20
    maxWait: 60000
    maxIdle: 8
    minIdle: 8
    initialSize: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: 
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
          
          #自动创建表
  jpa:
      hibernate:
  #      ddl-auto: create #ddl-auto:设为create表示每次都重写建表
        ddl-auto: update # ddl-auto:设为update表示每次都不会重写建表
  #      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
      database: MYSQL
      databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
###########################################################################################          
eureka:
  client:
    registerWithEureka: true #是否将自己注册到eureka服务中，本身就是所有无需注册
    fetchRegistry: true #是否从eureka服务中获取信息
    serviceUrl: #Eureka客户端与Eureka服务端交互地址
      defaultZone: http://oriki:1234@127.0.0.1:6868/eureka/,http://oriki:1234@127.0.0.1:6869/eureka/
      # http://127.0.0.1:6868/eureka/ ,http://127.0.0.1:6869/eureka/
    #eurekaServerConnectionTimeoutSeconds: 60
    #eurekaServerReadTimeoutSeconds: 60
  instance:
    prefer-ip-address: true #将自己的ip注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例Id
    #lease-expiration-duration-in-seconds: 30  #续约更新时间间隔(默认30秒)
    #lease-renewal-interval-in-seconds: 90 #续约到期时间（默认90秒）
    #leaseRenewalIntervalInSecondes: 90 #心跳时间
#  server:
#    enable-self-preservation: false #禁用自我保护模式
#    eviction-interval-timer-in-ms: 60000 #清理间隔（单位毫秒，默认是60*1000）

###########################################################################################
# 修改负载均衡算法：默认是轮询，这里修改为了随机访问
itcast-microservice-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

###########################################################################################
logging:
  level:
    root: info
# org.springframework.web:DEBUG
  file: /log/log/order.log


#配置MyBatis环境  别名扫描
mybatis:
#  type-aliases-package: cn.itcast.microservice.pojo
#  config-locations:  classpath:mybatis/mybatis-config.xml

#加载Mybatis核心配置文件
#  mapper-locations: classpath:mapper/*Mapper.xml

