server:
  port: ${port} #

spring:
  application:
    name: itcast-microservice-web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# = = = = = = = = = = = = = = = == = = = = = = = = = == = = = = = = = = = = = = = =


###########################################################################################

eureka:
  client:
    registerWithEureka: true #
    fetchRegistry: true #
    serviceUrl: #ои
      defaultZone: http://oriki:1234@127.0.0.1:6868/eureka/,http://oriki:1234@127.0.0.1:6869/eureka/
    #eurekaServerConnectionTimeoutSeconds: 60
    #eurekaServerReadTimeoutSeconds: 60
  instance:
    prefer-ip-address: true #
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #
    #lease-expiration-duration-in-seconds: 30  #
    #lease-renewal-interval-in-seconds: 90 #
    #leaseRenewalIntervalInSecondes: 90 #
###########################################################################################
logging:
  level:
    root: info
# org.springframework.web:DEBUG
  file: /log/log/zuul.log

