server:
  port: ${port} #服务端口

spring:
  application:
    name: itcast-microservice-sleuth    
# = = = = = = = = = = = = = = = == = = = = = = = = = == = = = = = = = = = = = = = =
# = = = = = = = = = = = = = = = == = = = = = = = = = == = = = = = = = = = = = = = =
eureka:
  client:
    registerWithEureka: true #是否将自己注册到eureka服务中，本身就是所有无需注册
    fetchRegistry: true #是否从eureka服务中获取信息
    serviceUrl: #Eureka客户端与Eureka服务端交互地址
      defaultZone: http://oriki:1234@127.0.0.1:6868/eureka/,http://oriki:1234@127.0.0.1:6869/eureka/
  instance:
    prefer-ip-address: true #将自己的ip注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例Id
# = = = = = = = = = = = = = = = == = = = = = = = = = == = = = = = = = = = = = = = =
logging:
  path: logs
  file: ${logging.path}/sleuth.log
  level:
    com.easystudio: INFO
    root: INFO
    org:
      hibernate.SQL: INFO
      springframework: 
        cloud.task: DEBUG
        web.servlet.DispatcherServlet: DEBUG
log4j.logger.org.springframework:
  jdbc: DEBUG
  batch: DEBUG